set verify off
CREATE OR REPLACE PACKAGE &&cwms_schema..test_cwms_measurements AS
    --%suite(Test measurements from cwms_stream package code)
    --%rollback(manual)

    --%beforeall (setup)
    procedure  setup;
    --%afterall(teardown)
    procedure  teardown;

    --%test(Test roundtrip store and retrieve with supplemental meas data)
    PROCEDURE test_store_and_retrieve;
    --%test(Test roundtrip store and retrieve with new USGS public api xml format)
    PROCEDURE test_store_and_retrieve_usgs;
    --%test(Test retrieval by id with filters)
    PROCEDURE test_retrieve_by_id;
    --%test(Test XML retrieval by id with filters)
    PROCEDURE test_retrieve_xml_by_id;
    --%test(Test legacy measurement number range filter)
    PROCEDURE test_legacy_range_filter;
    --%test(Test deletion by exact measurement id, including UUID)
    PROCEDURE test_delete_by_id;
END test_cwms_measurements;
/
SHOW ERRORS;

-- DROP TABLE xml_output_table;
--
-- CREATE TABLE xml_output_table (
--                                   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                                   xml_data CLOB
-- );
--
-- DROP TABLE xml_output_table_usgs;
--
-- CREATE TABLE xml_output_table_usgs (
--                                   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                                   xml_data CLOB
-- );

-- Create the test package body
CREATE OR REPLACE PACKAGE BODY &&cwms_schema..test_cwms_measurements AS

    PROCEDURE setup IS
    BEGIN
        teardown;
        cwms_loc.store_location(
                p_location_id  => 'StreamTestLoc',
                p_time_zone_id => 'UTC',
                p_db_office_id => '&&office_id');
        cwms_loc.store_location(
                p_location_id  => 'StreamTestLoc2',
                p_time_zone_id => 'UTC',
                p_db_office_id => '&&office_id');
        commit;
    END setup;

    PROCEDURE teardown IS
    BEGIN
       begin
           cwms_loc.delete_location(
              p_location_id   => 'StreamTestLoc',
              p_delete_action => cwms_util.delete_all,
              p_db_office_id  => '&&office_id');
           cwms_loc.delete_location(
              p_location_id   => 'StreamTestLoc2',
              p_delete_action => cwms_util.delete_all,
              p_db_office_id  => '&&office_id');
       exception
           when others then null;
       end;
    END teardown;

    PROCEDURE test_store_and_retrieve IS
        l_meas_xml_str CLOB;
        l_meas_xml     XMLTYPE;
        l_retrieved_xml_str CLOB;
        l_datetime_str VARCHAR2(32) := '2023-02-24T17:10:00Z';
        l_office_id    VARCHAR2(16) := '&&office_id';
        l_location_id  VARCHAR2(57) := 'StreamTestLoc';
        l_location_id2  VARCHAR2(57) := 'StreamTestLoc2';
        l_elev_unit    VARCHAR2(16) := 'ft';
        l_flow_unit    VARCHAR2(16) := 'cfs';
        l_temp_unit    VARCHAR2(16) := 'F';
        l_area_unit    VARCHAR2(16) := 'ft2';
        l_velocity_unit VARCHAR2(16) := 'ft/s';
    BEGIN

        l_meas_xml_str :=
                '<measurement height-unit=":elev_unit" flow-unit=":flow_unit" temp-unit=":temp_unit" area-unit=":area_unit" velocity-unit=":velocity_unit" used="true" office-id=":office_id">
                    <agency>USACE</agency>
                    <date>:datetime</date>
                    <location>:location</location>
                    <number>17</number>
                    <stream-flow-measurement>
                        <gage-height>10.0</gage-height>
                        <flow>1.0</flow>
                        <quality>Unspecified</quality>
                    </stream-flow-measurement>
                    <supplemental-stream-flow-measurement>
                        <channel-flow>100.0</channel-flow>
                        <overbank-flow>101.0</overbank-flow>
                        <overbank-max-depth>102.0</overbank-max-depth>
                        <channel-max-depth>103.0</channel-max-depth>
                        <avg-velocity>104.0</avg-velocity>
                        <surface-velocity>105.0</surface-velocity>
                        <max-velocity>106.0</max-velocity>
                        <effective-flow-area>107.0</effective-flow-area>
                        <cross-sectional-area>108.0</cross-sectional-area>
                        <mean-gage>109.0</mean-gage>
                        <top-width>110.0</top-width>
                        <main-channel-area>111.0</main-channel-area>
                        <overbank-area>112.0</overbank-area>
                    </supplemental-stream-flow-measurement>
                </measurement>';

        l_meas_xml_str := REPLACE(l_meas_xml_str, ':office_id', l_office_id);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':elev_unit', l_elev_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':flow_unit', l_flow_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':temp_unit', l_temp_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':area_unit', l_area_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':velocity_unit', l_velocity_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':location',  l_location_id);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':datetime',  l_datetime_str);

        -- Store the XML
        cwms_stream.store_meas_xml(
                p_xml            => l_meas_xml_str,
                p_fail_if_exists => 'F');

        -- Retrieve the XML
        l_retrieved_xml_str := cwms_stream.retrieve_meas_xml(
                p_location_id_mask => l_location_id,
                p_unit_system      => 'EN',
                p_office_id_mask   => l_office_id);

        ut.expect(l_retrieved_xml_str).to_be_like('%<number>17</number>%');
        ut.expect(l_retrieved_xml_str).to_be_like('%<gage-height>10</gage-height>%');
        ut.expect(l_retrieved_xml_str).to_be_like('%<channel-flow>100</channel-flow>%');

        -- Now store a second measurement with no gage-height or flow in the stream-flow-measurement element
        l_meas_xml_str :=
                '<measurement height-unit=":elev_unit" flow-unit=":flow_unit" temp-unit=":temp_unit" area-unit=":area_unit" velocity-unit=":velocity_unit" used="true" office-id=":office_id">
                    <agency>USACE</agency>
                    <date>:datetime</date>
                    <location>:location</location>
                    <number>18</number>
                    <stream-flow-measurement>
                        <quality>Unspecified</quality>
                    </stream-flow-measurement>
                    <supplemental-stream-flow-measurement>
                        <channel-flow>100.0</channel-flow>
                        <overbank-flow>101.0</overbank-flow>
                        <overbank-max-depth>102.0</overbank-max-depth>
                        <channel-max-depth>103.0</channel-max-depth>
                        <avg-velocity>104.0</avg-velocity>
                        <surface-velocity>105.0</surface-velocity>
                        <max-velocity>106.0</max-velocity>
                        <effective-flow-area>107.0</effective-flow-area>
                        <cross-sectional-area>108.0</cross-sectional-area>
                        <mean-gage>109.0</mean-gage>
                        <top-width>110.0</top-width>
                        <main-channel-area>111.0</main-channel-area>
                        <overbank-area>112.0</overbank-area>
                    </supplemental-stream-flow-measurement>
                </measurement>';

        l_meas_xml_str := REPLACE(l_meas_xml_str, ':office_id', l_office_id);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':elev_unit', l_elev_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':flow_unit', l_flow_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':temp_unit', l_temp_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':area_unit', l_area_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':velocity_unit', l_velocity_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':location',  l_location_id2);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':datetime',  l_datetime_str);

        -- Store the XML
        cwms_stream.store_meas_xml(
                p_xml            => l_meas_xml_str,
                p_fail_if_exists => 'F');

        -- Retrieve the XML
        l_retrieved_xml_str := cwms_stream.retrieve_meas_xml(
                p_location_id_mask => l_location_id2,
                p_unit_system      => 'EN',
                p_office_id_mask   => l_office_id);

        ut.expect(l_retrieved_xml_str).to_be_like('%<number>18</number>%');
        -- Verify that the gage-height and flow elements are not present in the retrieved XML since they were removed in the second store.
        ut.expect(l_retrieved_xml_str).not_to_be_like('%<gage-height>%');
        ut.expect(l_retrieved_xml_str).not_to_be_like('%<flow>%');

        -- test with gage-height but no flow
        l_meas_xml_str :=
                '<measurement height-unit=":elev_unit" flow-unit=":flow_unit" temp-unit=":temp_unit" area-unit=":area_unit" velocity-unit=":velocity_unit" used="true" office-id=":office_id">
                    <agency>USACE</agency>
                    <date>:datetime</date>
                    <location>:location</location>
                    <number>18</number>
                    <stream-flow-measurement>
                        <gage-height>10.0</gage-height>
                        <quality>Unspecified</quality>
                    </stream-flow-measurement>
                    <supplemental-stream-flow-measurement>
                        <channel-flow>100.0</channel-flow>
                        <overbank-flow>101.0</overbank-flow>
                        <overbank-max-depth>102.0</overbank-max-depth>
                        <channel-max-depth>103.0</channel-max-depth>
                        <avg-velocity>104.0</avg-velocity>
                        <surface-velocity>105.0</surface-velocity>
                        <max-velocity>106.0</max-velocity>
                        <effective-flow-area>107.0</effective-flow-area>
                        <cross-sectional-area>108.0</cross-sectional-area>
                        <mean-gage>109.0</mean-gage>
                        <top-width>110.0</top-width>
                        <main-channel-area>111.0</main-channel-area>
                        <overbank-area>112.0</overbank-area>
                    </supplemental-stream-flow-measurement>
                </measurement>';

        l_meas_xml_str := REPLACE(l_meas_xml_str, ':office_id', l_office_id);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':elev_unit', l_elev_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':flow_unit', l_flow_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':temp_unit', l_temp_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':area_unit', l_area_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':velocity_unit', l_velocity_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':location',  l_location_id2);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':datetime',  l_datetime_str);

        -- Store the XML
        cwms_stream.store_meas_xml(
                p_xml            => l_meas_xml_str,
                p_fail_if_exists => 'F');

        -- Retrieve the XML
        l_retrieved_xml_str := cwms_stream.retrieve_meas_xml(
                p_location_id_mask => l_location_id2,
                p_unit_system      => 'EN',
                p_office_id_mask   => l_office_id);

        ut.expect(l_retrieved_xml_str).to_be_like('%<number>18</number>%');
        -- Verify that the gage-height and flow elements are not present in the retrieved XML since they were removed in the second store.
        ut.expect(l_retrieved_xml_str).to_be_like('%<gage-height>10</gage-height>%');
        ut.expect(l_retrieved_xml_str).not_to_be_like('%<flow>%');

        --test with flow but no gage-height
        l_meas_xml_str :=
                '<measurement height-unit=":elev_unit" flow-unit=":flow_unit" temp-unit=":temp_unit" area-unit=":area_unit" velocity-unit=":velocity_unit" used="true" office-id=":office_id">
                    <agency>USACE</agency>
                    <date>:datetime</date>
                    <location>:location</location>
                    <number>18</number>
                    <stream-flow-measurement>
                        <flow>1.0</flow>
                        <quality>Unspecified</quality>
                    </stream-flow-measurement>
                    <supplemental-stream-flow-measurement>
                        <channel-flow>100.0</channel-flow>
                        <overbank-flow>101.0</overbank-flow>
                        <overbank-max-depth>102.0</overbank-max-depth>
                        <channel-max-depth>103.0</channel-max-depth>
                        <avg-velocity>104.0</avg-velocity>
                        <surface-velocity>105.0</surface-velocity>
                        <max-velocity>106.0</max-velocity>
                        <effective-flow-area>107.0</effective-flow-area>
                        <cross-sectional-area>108.0</cross-sectional-area>
                        <mean-gage>109.0</mean-gage>
                        <top-width>110.0</top-width>
                        <main-channel-area>111.0</main-channel-area>
                        <overbank-area>112.0</overbank-area>
                    </supplemental-stream-flow-measurement>
                </measurement>';

        l_meas_xml_str := REPLACE(l_meas_xml_str, ':office_id', l_office_id);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':elev_unit', l_elev_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':flow_unit', l_flow_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':temp_unit', l_temp_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':area_unit', l_area_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':velocity_unit', l_velocity_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':location',  l_location_id2);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':datetime',  l_datetime_str);

        -- Store the XML
        cwms_stream.store_meas_xml(
                p_xml            => l_meas_xml_str,
                p_fail_if_exists => 'F');

        -- Retrieve the XML
        l_retrieved_xml_str := cwms_stream.retrieve_meas_xml(
                p_location_id_mask => l_location_id2,
                p_unit_system      => 'EN',
                p_office_id_mask   => l_office_id);

        ut.expect(l_retrieved_xml_str).to_be_like('%<number>18</number>%');
        -- Verify that the gage-height and flow elements are not present in the retrieved XML since they were removed in the second store.
        ut.expect(l_retrieved_xml_str).not_to_be_like('%<gage-height>%');
        ut.expect(l_retrieved_xml_str).to_be_like('%<flow>1</flow>%');
    END test_store_and_retrieve;

    PROCEDURE test_store_and_retrieve_usgs IS
        l_meas_xml_str CLOB;
        l_meas_xml     XMLTYPE;
        l_retrieved_xml_str CLOB;
        l_datetime_str VARCHAR2(32) := '2023-02-24T17:10:00Z';
        l_office_id    VARCHAR2(16) := '&&office_id';
        l_location_id  VARCHAR2(57) := 'StreamTestLoc';
        l_elev_unit    VARCHAR2(16) := 'ft';
        l_flow_unit    VARCHAR2(16) := 'cfs';
        l_temp_unit    VARCHAR2(16) := 'F';
        l_area_unit    VARCHAR2(16) := 'ft2';
        l_velocity_unit VARCHAR2(16) := 'ft/s';
    BEGIN

        l_meas_xml_str :=
                '<measurement height-unit=":elev_unit" flow-unit=":flow_unit" temp-unit=":temp_unit" used="true" office-id=":office_id">
                    <agency>USGS</agency>
                    <party>:office_id</party>
                    <wm-comments>Test</wm-comments>
                    <date>2009-04-17T21:00:00Z</date>
                    <location>:location</location>
                    <number>89</number>
                    <stream-flow-measurement>
                        <gage-height>13.25</gage-height>
                        <flow>3460.0</flow>
                        <quality>Fair</quality>
                    </stream-flow-measurement>
                    <usgs-measurement>
                        <remarks>Import testing</remarks>
                        <current-rating>0.1</current-rating>
                        <control-condition/>
                        <shift-used>10.0</shift-used>
                        <percent-difference>0.5</percent-difference>
                        <flow-adjustment>MEAS</flow-adjustment>
                        <delta-height>11.0</delta-height>
                        <delta-time>12.0</delta-time>
                        <air-temp>60.0</air-temp>
                        <water-temp>68.0</water-temp>
                    </usgs-measurement>
                </measurement>';

        l_meas_xml_str := REPLACE(l_meas_xml_str, ':office_id', l_office_id);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':elev_unit', l_elev_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':flow_unit', l_flow_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':temp_unit', l_temp_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':area_unit', l_area_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':velocity_unit', l_velocity_unit);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':location',  l_location_id);
        l_meas_xml_str := REPLACE(l_meas_xml_str, ':datetime',  l_datetime_str);

        -- Store the XML
        cwms_stream.store_meas_xml(
                p_xml            => l_meas_xml_str,
                p_fail_if_exists => 'F');

        -- Retrieve the XML
        l_retrieved_xml_str := cwms_stream.retrieve_meas_xml(
                p_location_id_mask => l_location_id,
                p_unit_system      => 'EN',
                p_office_id_mask   => l_office_id);

        ut.expect(l_retrieved_xml_str).to_be_like('%<number>89</number>%');
        ut.expect(l_retrieved_xml_str).to_be_like('%<gage-height>13.25</gage-height>%');
        ut.expect(l_retrieved_xml_str).to_be_like('%<remarks>Import testing</remarks>%');
    END test_store_and_retrieve_usgs;

    PROCEDURE test_retrieve_by_id IS
        l_meas_tab  streamflow_meas_tab_t;
        l_meas2_tab streamflow_meas2_tab_t;
        l_location_id VARCHAR2(57) := 'StreamTestLoc';
        l_office_id    VARCHAR2(16) := '&&office_id';
        l_xml CLOB;
    BEGIN
        -- Store its own measurements for testing
        l_xml := '<measurement height-unit="ft" flow-unit="cfs" used="true" office-id="'||l_office_id||'">
                    <agency>USACE</agency>
                    <date>2023-05-01T12:00:00Z</date>
                    <location>'||l_location_id||'</location>
                    <number>101</number>
                    <stream-flow-measurement>
                        <gage-height>10.0</gage-height>
                        <flow>100.0</flow>
                    </stream-flow-measurement>
                  </measurement>';
        cwms_stream.store_meas_xml(l_xml, 'F');

        l_xml := '<measurement height-unit="ft" flow-unit="cfs" used="true" office-id="'||l_office_id||'">
                    <agency>USACE</agency>
                    <date>2023-05-02T12:00:00Z</date>
                    <location>'||l_location_id||'</location>
                    <number>550e8400-e29b-41d4-a716-446655440000</number>
                    <stream-flow-measurement>
                        <gage-height>20.0</gage-height>
                        <flow>200.0</flow>
                    </stream-flow-measurement>
                  </measurement>';
        cwms_stream.store_meas_xml(l_xml, 'F');

        -- Test exact match for legacy number '101'
        l_meas_tab := cwms_stream.retrieve_streamflow_meas_by_id(
            p_location_id_mask => l_location_id,
            p_meas_id          => '101');
        ut.expect(l_meas_tab.count).to_equal(1);
        ut.expect(l_meas_tab(1).meas_number).to_equal('101');

        -- Test exact match for UUID '550e8400-e29b-41d4-a716-446655440000'
        l_meas2_tab := cwms_stream.retrieve_meas_by_id(
            p_location_id_mask => l_location_id,
            p_meas_id          => '550e8400-e29b-41d4-a716-446655440000');
        ut.expect(l_meas2_tab.count).to_equal(1);
        ut.expect(l_meas2_tab(1).meas_number).to_equal('550e8400-e29b-41d4-a716-446655440000');

        -- Test retrieval with null meas_id (should return both '101' and '550e8400-e29b-41d4-a716-446655440000')
        l_meas2_tab := cwms_stream.retrieve_meas_by_id(
            p_location_id_mask => l_location_id,
            p_meas_id          => null,
            p_min_date         => to_date('2023-05-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            p_max_date         => to_date('2023-05-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            p_time_zone        => 'UTC');
        ut.expect(l_meas2_tab.count).to_be_greater_or_equal(2);

    END test_retrieve_by_id;

    PROCEDURE test_retrieve_xml_by_id IS
        l_xml CLOB;
        l_location_id VARCHAR2(57) := 'StreamTestLoc';
    BEGIN
        -- Test exact match XML for '101'
        l_xml := cwms_stream.retrieve_meas_xml_by_id(
            p_location_id_mask => l_location_id,
            p_meas_id          => '101');
        ut.expect(l_xml).to_be_not_null();
        ut.expect(l_xml).to_be_like('%<number>101</number>%');

        -- Test exact match XML for UUID
        l_xml := cwms_stream.retrieve_meas_xml_by_id(
            p_location_id_mask => l_location_id,
            p_meas_id          => '550e8400-e29b-41d4-a716-446655440000');
        ut.expect(l_xml).to_be_not_null();
        ut.expect(l_xml).to_be_like('%<number>550e8400-e29b-41d4-a716-446655440000</number>%');

        -- Test null meas_id XML
        l_xml := cwms_stream.retrieve_meas_xml_by_id(
            p_location_id_mask => l_location_id,
            p_meas_id          => null,
            p_min_date         => to_date('2023-05-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            p_max_date         => to_date('2023-05-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            p_time_zone        => 'UTC');
        ut.expect(l_xml).to_be_like('%<number>101</number>%');
        ut.expect(l_xml).to_be_like('%<number>550e8400-e29b-41d4-a716-446655440000</number>%');

    END test_retrieve_xml_by_id;

    PROCEDURE test_legacy_range_filter IS
        l_meas_tab  streamflow_meas2_tab_t;
        l_location_id VARCHAR2(57) := 'StreamTestLoc';
        l_office_id    VARCHAR2(16) := '&&office_id';
        l_xml CLOB;
        l_found_uuid BOOLEAN := FALSE;
    BEGIN
        -- Store several legacy measurements
        -- '10', '20', '30'
        for i in 1..3 loop
            l_xml := '<measurement height-unit="ft" flow-unit="cfs" used="true" office-id="'||l_office_id||'">
                        <agency>USGS</agency>
                        <date>2023-01-0'||i||'T12:00:00Z</date>
                        <location>'||l_location_id||'</location>
                        <number>'||(i*10)||'</number>
                        <stream-flow-measurement>
                            <gage-height>'||(i*10)||'</gage-height>
                            <flow>'||(i*100)||'</flow>
                        </stream-flow-measurement>
                      </measurement>';
            cwms_stream.store_meas_xml(l_xml, 'F');
        end loop;

        -- Store a "UUID-like" measurement
        l_xml := '<measurement height-unit="ft" flow-unit="cfs" used="true" office-id="'||l_office_id||'">
                    <agency>USGS</agency>
                    <date>2023-01-04T12:00:00Z</date>
                    <location>'||l_location_id||'</location>
                    <number>551e8400-e29b-41d4-a716-446655440000</number>
                    <stream-flow-measurement>
                        <gage-height>40</gage-height>
                        <flow>400</flow>
                    </stream-flow-measurement>
                  </measurement>';
        cwms_stream.store_meas_xml(l_xml, 'F');

        -- Test 1: Range filter that includes '20' but excludes '10' and '30'
        l_meas_tab := cwms_stream.retrieve_meas_objs(
            p_location_id_mask => l_location_id,
            p_min_num          => '15',
            p_max_num          => '25',
            p_min_date         => to_date('2023-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            p_max_date         => to_date('2023-01-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            p_time_zone        => 'UTC');
        ut.expect(l_meas_tab.count).to_equal(1);
        ut.expect(l_meas_tab(1).meas_number).to_equal('20');

        -- Test 2: Verify UUID is excluded when range filter is used
        l_meas_tab := cwms_stream.retrieve_meas_objs(
            p_location_id_mask => l_location_id,
            p_min_num          => '9',
            p_max_num          => null,
            p_min_date         => to_date('2023-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            p_max_date         => to_date('2023-01-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            p_time_zone        => 'UTC');
        -- Should return at least 3 legacy ones ('10', '20', '30'), and not the UUID one.
        -- UUIDs (not matching ^[0-9A-Fa-f]{1,8}$) should definitely be excluded.
        for i in 1..l_meas_tab.count loop
            ut.expect(l_meas_tab(i).meas_number).to_match('^[0-9]+$');
        end loop;

        -- Test 3: Null range returns everything (including UUID)
        l_meas_tab := cwms_stream.retrieve_meas_objs(
            p_location_id_mask => l_location_id,
            p_min_num          => null,
            p_max_num          => null,
            p_min_date         => to_date('2023-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            p_max_date         => to_date('2023-01-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            p_time_zone        => 'UTC');
        ut.expect(l_meas_tab.count).to_be_greater_or_equal(4);

        -- Explicitly check that our UUID measurement was returned
        for i in 1..l_meas_tab.count loop
            if l_meas_tab(i).meas_number = '551e8400-e29b-41d4-a716-446655440000' then
                l_found_uuid := TRUE;
                exit;
            end if;
        end loop;

        ut.expect(l_found_uuid).to_be_true();
    END test_legacy_range_filter;

    PROCEDURE test_delete_by_id IS
        l_meas_tab    streamflow_meas2_tab_t;
        l_location_id VARCHAR2(57) := 'StreamTestLoc';
        l_office_id   VARCHAR2(16) := '&&office_id';
        l_xml         CLOB;
        l_uuid        VARCHAR2(36) := '552e8400-e29b-41d4-a716-446655440000';
        l_raised      BOOLEAN := FALSE;
    BEGIN
        -- Store a legacy-numbered measurement and a UUID-numbered measurement
        l_xml := '<measurement height-unit="ft" flow-unit="cfs" used="true" office-id="'||l_office_id||'">
                    <agency>USACE</agency>
                    <date>2023-06-01T12:00:00Z</date>
                    <location>'||l_location_id||'</location>
                    <number>201</number>
                    <stream-flow-measurement>
                        <gage-height>10.0</gage-height>
                        <flow>100.0</flow>
                    </stream-flow-measurement>
                  </measurement>';
        cwms_stream.store_meas_xml(l_xml, 'F');

        l_xml := '<measurement height-unit="ft" flow-unit="cfs" used="true" office-id="'||l_office_id||'">
                    <agency>USACE</agency>
                    <date>2023-06-02T12:00:00Z</date>
                    <location>'||l_location_id||'</location>
                    <number>'||l_uuid||'</number>
                    <stream-flow-measurement>
                        <gage-height>20.0</gage-height>
                        <flow>200.0</flow>
                    </stream-flow-measurement>
                  </measurement>';
        cwms_stream.store_meas_xml(l_xml, 'F');

        -- Sanity check: the UUID measurement exists before delete
        l_meas_tab := cwms_stream.retrieve_meas_by_id(
            p_location_id_mask => l_location_id,
            p_meas_id          => l_uuid);
        ut.expect(l_meas_tab.count).to_equal(1);

        -- Delete only the UUID measurement by id
        cwms_stream.delete_streamflow_meas_by_id(
            p_location_id_mask => l_location_id,
            p_meas_id          => l_uuid,
            p_office_id_mask   => l_office_id);

        -- Verify the UUID measurement is gone
        l_meas_tab := cwms_stream.retrieve_meas_by_id(
            p_location_id_mask => l_location_id,
            p_meas_id          => l_uuid);
        ut.expect(l_meas_tab.count).to_equal(0);

        -- Verify the legacy measurement was NOT affected by the UUID delete
        l_meas_tab := cwms_stream.retrieve_meas_by_id(
            p_location_id_mask => l_location_id,
            p_meas_id          => '201');
        ut.expect(l_meas_tab.count).to_equal(1);

        -- Delete the legacy measurement by id too, proving exact-match delete also works for legacy numbers
        cwms_stream.delete_streamflow_meas_by_id(
            p_location_id_mask => l_location_id,
            p_meas_id          => '201',
            p_office_id_mask   => l_office_id);

        l_meas_tab := cwms_stream.retrieve_meas_by_id(
            p_location_id_mask => l_location_id,
            p_meas_id          => '201');
        ut.expect(l_meas_tab.count).to_equal(0);

        -- A null p_meas_id must be rejected rather than silently bulk-deleting
        BEGIN
            cwms_stream.delete_streamflow_meas_by_id(
                p_location_id_mask => l_location_id,
                p_meas_id          => null,
                p_office_id_mask   => l_office_id);
        EXCEPTION
            WHEN others THEN
                l_raised := TRUE;
        END;
        ut.expect(l_raised).to_be_true();

    END test_delete_by_id;

END test_cwms_measurements;
/
SHOW ERRORS;


