/*
 * Copyright (c) 2026
 * United States Army Corps of Engineers - Hydrologic Engineering Center (USACE/HEC)
 * All Rights Reserved.  USACE PROPRIETARY/CONFIDENTIAL.
 * Source may not be released without written approval from HEC
 */

INSERT INTO AT_PUBLISHED_TS (LOCATION_CODE, PARAMETER_CODE, TS_CODE)
SELECT 
    LOCATION_CODE,
    PARAMETER_CODE,
    TS_CODE
FROM (
    /* Primary Mappings */
    SELECT LOCATION_CODE, 10 /* Elev */ AS PARAMETER_CODE, TS_CODE_ELEV AS TS_CODE FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_ELEV IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 19 /* Precip */, TS_CODE_PRECIP FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_PRECIP IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 23 /* Stage */, TS_CODE_STAGE FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_STAGE IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 311 /* Flow-In */, TS_CODE_INFLOW FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_INFLOW IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 312 /* Flow-Out */, TS_CODE_OUTFLOW FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_OUTFLOW IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 314 /* Flow-Spill */, TS_CODE_SUR_RELEASE FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_SUR_RELEASE IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 18 /* Power */, TS_CODE_POWER_GEN FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_POWER_GEN IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 316 /* Temp-Air */, TS_CODE_TEMP_AIR FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_TEMP_AIR IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 317 /* Temp-Water */, TS_CODE_TEMP_WATER FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_TEMP_WATER IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 305 /* Conc-DO */, TS_CODE_DO FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_DO IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 6 /* Cond */, TS_CODE_COND FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_COND IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 17 /* pH */, TS_CODE_PH FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_PH IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 16 /* Opening */, TS_CODE_OPENING FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_OPENING IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 3 /* Dir */, TS_CODE_WIND_DIR FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_WIND_DIR IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 22 /* Speed */, TS_CODE_WIND_SPEED FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_WIND_SPEED IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 29 /* Volt */, TS_CODE_VOLT FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_VOLT IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 1 /* % */, TS_CODE_PCT_FLOOD FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_PCT_FLOOD IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 32 /* Irrad */, TS_CODE_IRRAD FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_IRRAD IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 12 /* Evap */, TS_CODE_EVAP FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_EVAP IS NOT NULL
    UNION ALL
    /* TODO: figure out how to map these to parameters. */
    SELECT LOCATION_CODE, 000000000000 /* Placeholder */, TS_CODE_STOR_FLOOD FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_STOR_FLOOD IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 000000000000 /* Placeholder */, TS_CODE_STOR_DROUGHT FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_STOR_DROUGHT IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 000000000000 /* Placeholder */, TS_CODE_ELEV_TW FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_ELEV_TW IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 000000000000 /* Placeholder */, TS_CODE_STAGE_TW FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_STAGE_TW IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 000000000000 /* Placeholder */, TS_CODE_RULE_CURVE_ELEV FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_RULE_CURVE_ELEV IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 000000000000 /* Placeholder */, TS_CODE_PCT_CON FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_PCT_CON IS NOT NULL
) src;

COMMIT;
