/*
 * Copyright (c) 2026
 * United States Army Corps of Engineers - Hydrologic Engineering Center (USACE/HEC)
 * All Rights Reserved.  USACE PROPRIETARY/CONFIDENTIAL.
 * Source may not be released without written approval from HEC
 */

--------------------------------------------------------------------------------
-- Migrates AT_A2W_TS_CODES_BY_LOC into the normalized tables defined in
-- at_published.sql and at_a2w_attributes.sql:
--
--   AT_A2W_ATTRIBUTES   - app-specific display/notes metadata, 1:1 by LOCATION_CODE
--   AT_PUBLISHED_TS     - one row per non-null TS_CODE_* column
--   AT_PUBLISHED_RATING - one row per non-null RATING_CODE_* column
--
-- Not idempotent. This is a one-time cutover script - rerunning it will
-- collide with the primary keys on all three target tables.
--
-- Known gap: rows where OPENING_SOURCE_OBJ = 'OBJ' have a TS_CODE_OPENING
-- value that is actually an object reference, not a real TS_CODE. Those rows
-- are deliberately excluded from the AT_PUBLISHED_TS insert below - inserting
-- them would violate the AT_PUBLISHED_TS_FK_TS foreign key (and, if the value
-- happened to coincide with a real TS_CODE, the AT_PUBLISHED_TS_T01 base
-- parameter trigger). OPENING_SOURCE_OBJ itself is preserved on
-- AT_A2W_ATTRIBUTES, but the underlying object code has no destination in the
-- new schema yet. Section 4 below reports how many rows this affects.
--------------------------------------------------------------------------------

-------------------------------------
-- 1. AT_A2W_ATTRIBUTES (1:1 copy) --
-------------------------------------
INSERT INTO AT_A2W_ATTRIBUTES (LOCATION_CODE, DATE_REFRESHED, NOTES, DISPLAY_FLAG, LAKE_SUMMARY_TF, OPENING_SOURCE_OBJ)
SELECT LOCATION_CODE, DATE_REFRESHED, NOTES, DISPLAY_FLAG, LAKE_SUMMARY_TF, OPENING_SOURCE_OBJ
FROM AT_A2W_TS_CODES_BY_LOC;

------------------------------------------------------------------------------
-- 2. AT_PUBLISHED_TS
--    DML error logging is used so a single bad row (e.g. a TS_CODE whose
--    base parameter doesn't match its PUBLISHED_ID - see AT_PUBLISHED_TS_T01)
--    is logged and skipped instead of aborting the whole migration.
------------------------------------------------------------------------------
BEGIN
   DBMS_ERRLOG.CREATE_ERROR_LOG('AT_PUBLISHED_TS');
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -955 THEN -- ORA-00955: name already used by an existing object
         RAISE;
      END IF;
END;
/

INSERT INTO AT_PUBLISHED_TS (LOCATION_CODE, PUBLISHED_ID, TS_CODE)
SELECT LOCATION_CODE, PUBLISHED_ID, TS_CODE
FROM (
    SELECT LOCATION_CODE, 'TS_ELEV' AS PUBLISHED_ID, TS_CODE_ELEV AS TS_CODE FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_ELEV IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_PRECIP', TS_CODE_PRECIP FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_PRECIP IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_STAGE', TS_CODE_STAGE FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_STAGE IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_INFLOW', TS_CODE_INFLOW FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_INFLOW IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_OUTFLOW', TS_CODE_OUTFLOW FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_OUTFLOW IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_STOR_FLOOD', TS_CODE_STOR_FLOOD FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_STOR_FLOOD IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_STOR_DROUGHT', TS_CODE_STOR_DROUGHT FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_STOR_DROUGHT IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_SUR_RELEASE', TS_CODE_SUR_RELEASE FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_SUR_RELEASE IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_ELEV_TW', TS_CODE_ELEV_TW FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_ELEV_TW IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_STAGE_TW', TS_CODE_STAGE_TW FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_STAGE_TW IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_RULE_CURVE_ELEV', TS_CODE_RULE_CURVE_ELEV FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_RULE_CURVE_ELEV IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_POWER_GEN', TS_CODE_POWER_GEN FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_POWER_GEN IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_TEMP_AIR', TS_CODE_TEMP_AIR FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_TEMP_AIR IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_TEMP_WATER', TS_CODE_TEMP_WATER FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_TEMP_WATER IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_DO', TS_CODE_DO FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_DO IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_COND', TS_CODE_COND FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_COND IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_PH', TS_CODE_PH FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_PH IS NOT NULL
    UNION ALL
    -- Only migrate TS_CODE_OPENING when it is actually a TS Code; rows
    -- flagged OPENING_SOURCE_OBJ = 'OBJ' are intentionally excluded (see gap note above).
    SELECT LOCATION_CODE, 'TS_OPENING', TS_CODE_OPENING FROM AT_A2W_TS_CODES_BY_LOC
     WHERE TS_CODE_OPENING IS NOT NULL AND NVL(OPENING_SOURCE_OBJ, 'TS') != 'OBJ'
    UNION ALL
    SELECT LOCATION_CODE, 'TS_WIND_DIR', TS_CODE_WIND_DIR FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_WIND_DIR IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_WIND_SPEED', TS_CODE_WIND_SPEED FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_WIND_SPEED IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_VOLT', TS_CODE_VOLT FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_VOLT IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_PCT_FLOOD', TS_CODE_PCT_FLOOD FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_PCT_FLOOD IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_PCT_CON', TS_CODE_PCT_CON FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_PCT_CON IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_IRRAD', TS_CODE_IRRAD FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_IRRAD IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'TS_EVAP', TS_CODE_EVAP FROM AT_A2W_TS_CODES_BY_LOC WHERE TS_CODE_EVAP IS NOT NULL
) src
LOG ERRORS INTO ERR$_AT_PUBLISHED_TS ('A2W_MIGRATION') REJECT LIMIT UNLIMITED;

------------------------------------------------------------------------------
-- 3. AT_PUBLISHED_RATING - same error-logging treatment as above, guarding
--    against AT_PUBLISHED_RATING_T01.
------------------------------------------------------------------------------
BEGIN
   DBMS_ERRLOG.CREATE_ERROR_LOG('AT_PUBLISHED_RATING');
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -955 THEN
         RAISE;
      END IF;
END;
/

INSERT INTO AT_PUBLISHED_RATING (LOCATION_CODE, PUBLISHED_ID, RATING_SPEC_CODE)
SELECT LOCATION_CODE, PUBLISHED_ID, RATING_SPEC_CODE
FROM (
    SELECT LOCATION_CODE, 'RATING_ELEV_STOR' AS PUBLISHED_ID, RATING_CODE_ELEV_STOR AS RATING_SPEC_CODE FROM AT_A2W_TS_CODES_BY_LOC WHERE RATING_CODE_ELEV_STOR IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'RATING_ELEV_AREA', RATING_CODE_ELEV_AREA FROM AT_A2W_TS_CODES_BY_LOC WHERE RATING_CODE_ELEV_AREA IS NOT NULL
    UNION ALL
    SELECT LOCATION_CODE, 'RATING_OUTLET_FLOW', RATING_CODE_OUTLET_FLOW FROM AT_A2W_TS_CODES_BY_LOC WHERE RATING_CODE_OUTLET_FLOW IS NOT NULL
) src
LOG ERRORS INTO ERR$_AT_PUBLISHED_RATING ('A2W_MIGRATION') REJECT LIMIT UNLIMITED;

------------------------------------------------------------------------------
-- 4. Review before committing - do not blindly COMMIT this script.
------------------------------------------------------------------------------

-- Row counts migrated:
SELECT 'AT_A2W_ATTRIBUTES' AS TARGET, COUNT(*) AS ROWS_INSERTED FROM AT_A2W_ATTRIBUTES
UNION ALL
SELECT 'AT_PUBLISHED_TS', COUNT(*) FROM AT_PUBLISHED_TS
UNION ALL
SELECT 'AT_PUBLISHED_RATING', COUNT(*) FROM AT_PUBLISHED_RATING;

-- Rows that failed AT_PUBLISHED_TS_T01 base-parameter validation (should be empty):
SELECT ORA_ERR_TAG$, ORA_ERR_MESG$, LOCATION_CODE, PUBLISHED_ID, TS_CODE
FROM ERR$_AT_PUBLISHED_TS;

-- Rows that failed AT_PUBLISHED_RATING_T01 base-parameter validation (should be empty):
SELECT ORA_ERR_TAG$, ORA_ERR_MESG$, LOCATION_CODE, PUBLISHED_ID, RATING_SPEC_CODE
FROM ERR$_AT_PUBLISHED_RATING;

-- Rows with an "OBJ"-sourced opening that were intentionally not migrated to
-- AT_PUBLISHED_TS - review whether these need a manual follow-up:
SELECT LOCATION_CODE, LOCATION_ID, TS_CODE_OPENING, OPENING_SOURCE_OBJ
FROM AT_A2W_TS_CODES_BY_LOC
WHERE TS_CODE_OPENING IS NOT NULL AND OPENING_SOURCE_OBJ = 'OBJ';

-- Once the counts and error logs above have been reviewed and look correct:
-- COMMIT;
