CREATE TABLE AT_A2W_TS_CODES_BY_LOC 
(
  LOCATION_ID VARCHAR2(199 BYTE) 
, DB_OFFICE_ID VARCHAR2(5 BYTE) 
, TS_CODE_ELEV NUMBER 
, TS_CODE_PRECIP NUMBER 
, TS_CODE_STAGE NUMBER 
, TS_CODE_INFLOW NUMBER 
, TS_CODE_OUTFLOW NUMBER 
, DATE_REFRESHED DATE NOT NULL 
, TS_CODE_STOR_FLOOD NUMBER 
, NOTES CLOB 
, DISPLAY_FLAG VARCHAR2(1 BYTE) DEFAULT 'F' NOT NULL 
, NUM_TS_CODES NUMBER DEFAULT 0 NOT NULL 
, TS_CODE_STOR_DROUGHT NUMBER 
, LAKE_SUMMARY_TF VARCHAR2(1 BYTE) DEFAULT 'F' NOT NULL 
, TS_CODE_SUR_RELEASE NUMBER 
, LOCATION_CODE NUMBER NOT NULL 
, TS_CODE_ELEV_TW NUMBER 
, TS_CODE_STAGE_TW NUMBER 
, TS_CODE_RULE_CURVE_ELEV NUMBER 
, TS_CODE_POWER_GEN NUMBER 
, TS_CODE_TEMP_AIR NUMBER 
, TS_CODE_TEMP_WATER NUMBER 
, TS_CODE_DO NUMBER 
, RATING_CODE_ELEV_STOR NUMBER 
, TS_CODE_COND NUMBER 
, TS_CODE_PH NUMBER 
, RATING_CODE_ELEV_AREA NUMBER 
, RATING_CODE_OUTLET_FLOW NUMBER 
, TS_CODE_OPENING NUMBER 
, OPENING_SOURCE_OBJ VARCHAR2(5 BYTE) 
, ts_code_wind_dir NUMBER
,TS_CODE_WIND_SPEED NUMBER
,TS_CODE_VOLT NUMBER
 ,TS_CODE_PCT_FLOOD NUMBER
 ,TS_CODE_PCT_CON NUMBER
, TS_CODE_IRRAD NUMBER
,  TS_CODE_EVAP NUMBER
) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL 
LOB (NOTES) STORE AS SYS_LOB0000204559C00010$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE CWMS_20AT_DATA 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
);

CREATE INDEX A2W_COUNTS_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_ID ASC, DB_OFFICE_ID ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX AT_A2W_ACTIVE_COND_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC, TS_CODE_COND ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX AT_A2W_ACTIVE_DO_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC, TS_CODE_DO ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX AT_A2W_ACTIVE_DROUGHT_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC, TS_CODE_STOR_DROUGHT ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX AT_A2W_ACTIVE_ELEV_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC, TS_CODE_ELEV ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX AT_A2W_ACTIVE_ELEV_TW_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC, TS_CODE_ELEV_TW ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX AT_A2W_ACTIVE_FLOOD_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC, TS_CODE_STOR_FLOOD ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX AT_A2W_ACTIVE_INFLOW_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC, TS_CODE_INFLOW ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX AT_A2W_ACTIVE_OUTFLOW_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC, TS_CODE_OUTFLOW ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX AT_A2W_ACTIVE_PH_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC, TS_CODE_PH ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX AT_A2W_ACTIVE_POWER_GEN_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC, TS_CODE_POWER_GEN ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX AT_A2W_ACTIVE_PRECIP_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC, TS_CODE_PRECIP ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX AT_A2W_ACTIVE_RATING_ES_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC, RATING_CODE_ELEV_STOR ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX AT_A2W_ACTIVE_RC_ELEV_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC, TS_CODE_RULE_CURVE_ELEV ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX AT_A2W_ACTIVE_STAGE_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC, TS_CODE_STAGE ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX AT_A2W_ACTIVE_STAGE_TW_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC, TS_CODE_STAGE_TW ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX AT_A2W_ACTIVE_SUR_RELEASE_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC, TS_CODE_SUR_RELEASE ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX AT_A2W_ACTIVE_TEMP_AIR_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC, TS_CODE_TEMP_AIR ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX AT_A2W_ACTIVE_TEMP_WATER_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC, TS_CODE_TEMP_WATER ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX AT_A2W_LOC_CODE_FLAG_IDX ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC, DISPLAY_FLAG ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX AT_A2W_TS_CODES_BY_LOC_PK ON AT_A2W_TS_CODES_BY_LOC (LOCATION_CODE ASC) 
LOGGING 
TABLESPACE CWMS_20DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE AT_A2W_TS_CODES_BY_LOC
ADD CONSTRAINT AT_A2W_TS_CODES_BY_LOC_PK PRIMARY KEY 
(
  LOCATION_CODE 
)
USING INDEX CWMS_20.AT_A2W_TS_CODES_BY_LOC_PK 
ENABLE;

ALTER TABLE AT_A2W_TS_CODES_BY_LOC
ADD CONSTRAINT AT_A2W_TS_CODES_BY_LOC_R01 FOREIGN KEY
(
  LOCATION_CODE 
)
REFERENCES AT_PHYSICAL_LOCATION
(
  LOCATION_CODE 
)
ENABLE;

COMMENT ON TABLE AT_A2W_TS_CODES_BY_LOC IS 'The AT_A2W_TS_CODES_BY_LOC table stores the WM choice of TS Codes representing a locations elevation, precipitation, stage, inflow, outflow, flood storage, drought storage, and surcharge releases. The TS Codes establish a 1:1 relationship between location and display in various nationwide/public reports. Additional details are in the column comments/';

COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.LOCATION_ID IS 'The Location this record applies to';

COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.DB_OFFICE_ID IS 'The office that the record is owned by';

COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.TS_CODE_ELEV IS 'The TS Code showing elevation (projects)';

COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.TS_CODE_PRECIP IS 'The TS Code showing precipitation at the project';

COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.TS_CODE_STAGE IS 'The TS Code showing stage (stream gages)';

COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.TS_CODE_INFLOW IS 'The TS Code showing inflow into the reservoir';

COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.TS_CODE_OUTFLOW IS 'The TS Code showing outflow through the project';

COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.DATE_REFRESHED IS 'The date this record was created/last updated';

COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.TS_CODE_STOR_FLOOD IS 'The TS Code showing calculated flood storage';

COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.NOTES IS 'Any notes generated by the initial data load or the WM through CMA';

COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.DISPLAY_FLAG IS 'Flag recording the WM choice to display this location in a hierarchy';

COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.NUM_TS_CODES IS 'Calculated count of TS Codes (+1 ea. for elev,precip,stage, etc.)';

COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.TS_CODE_STOR_DROUGHT IS 'The TS Code showing calculated drought/conservation storage storage';

COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.LAKE_SUMMARY_TF IS 'The flag recording if this location should be in the lake summary report';

COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.TS_CODE_SUR_RELEASE IS 'The TS Code showing Surchage Releases (flow)';

COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.OPENING_SOURCE_OBJ IS 'Use the Opening obj or TS Code (OBJ or TS)';

/