/*
 * Copyright (c) 2026
 * United States Army Corps of Engineers - Hydrologic Engineering Center (USACE/HEC)
 * All Rights Reserved.  USACE PROPRIETARY/CONFIDENTIAL.
 * Source may not be released without written approval from HEC
 */

CREATE TABLE CWMS_PUBLISHED_ID (
    PUBLISHED_ID VARCHAR2(24) NOT NULL,
    NAMESPACE VARCHAR2(32) NOT NULL,
    PUBLIC_NAME VARCHAR2(128) NOT NULL,
    BASE_PARAMETER_CODE NUMBER(14) NOT NULL,
    CONSTRAINT CWMS_PUBLISHED_ID_PK PRIMARY KEY (PUBLISHED_ID) USING INDEX TABLESPACE CWMS_20AT_DATA,
    CONSTRAINT CWMS_PUBLISHED_ID_U1 UNIQUE (NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE) USING INDEX TABLESPACE CWMS_20AT_DATA,
    CONSTRAINT CWMS_PUBLISHED_ID_FK1 FOREIGN KEY (BASE_PARAMETER_CODE) REFERENCES CWMS_BASE_PARAMETER (BASE_PARAMETER_CODE)
) TABLESPACE CWMS_20AT_DATA;

COMMENT ON TABLE CWMS_PUBLISHED_ID IS 'Static published identifier definitions';
COMMENT ON COLUMN CWMS_PUBLISHED_ID.PUBLISHED_ID IS 'Synthetic key for a reusable published identifier - e.g. TS_STAGE';
COMMENT ON COLUMN CWMS_PUBLISHED_ID.NAMESPACE IS 'Namespace that scopes the published identifier - e.g. PUBLISHED, REGI, etc.';
COMMENT ON COLUMN CWMS_PUBLISHED_ID.PUBLIC_NAME IS 'Public identifier name within the namespace - e.g. Stage Time Series';
COMMENT ON COLUMN CWMS_PUBLISHED_ID.BASE_PARAMETER_CODE IS 'Foreign key to AT_PARAMETER';

CREATE TABLE AT_PUBLISHED_TS (
    LOCATION_CODE NUMBER(14) NOT NULL,
    PUBLISHED_ID VARCHAR2(24) NOT NULL,
    TS_CODE NUMBER(14) NOT NULL,
    CONSTRAINT AT_PUBLISHED_TS_PK PRIMARY KEY (LOCATION_CODE, PUBLISHED_ID, TS_CODE) USING INDEX TABLESPACE CWMS_20AT_DATA,
    CONSTRAINT AT_PUBLISHED_TS_FK_LOC FOREIGN KEY (LOCATION_CODE) REFERENCES AT_PHYSICAL_LOCATION (LOCATION_CODE),
    CONSTRAINT AT_PUBLISHED_TS_FK_PUB FOREIGN KEY (PUBLISHED_ID) REFERENCES CWMS_PUBLISHED_ID (PUBLISHED_ID),
    CONSTRAINT AT_PUBLISHED_TS_FK_TS FOREIGN KEY (TS_CODE) REFERENCES AT_CWMS_TS_SPEC (TS_CODE)
) TABLESPACE CWMS_20AT_DATA;

COMMENT ON TABLE AT_PUBLISHED_TS IS 'Maps locations and published identifiers to their corresponding published time series';
COMMENT ON COLUMN AT_PUBLISHED_TS.LOCATION_CODE IS 'Foreign key to AT_PHYSICAL_LOCATION';
COMMENT ON COLUMN AT_PUBLISHED_TS.PUBLISHED_ID IS 'Foreign key to CWMS_PUBLISHED_ID';
COMMENT ON COLUMN AT_PUBLISHED_TS.TS_CODE IS 'Foreign key to AT_CWMS_TS_SPEC';

-- the base parameter of TS_CODE (via AT_CWMS_TS_SPEC -> AT_PARAMETER)
-- must match the BASE_PARAMETER_CODE of the referenced CWMS_PUBLISHED_ID row.
CREATE OR REPLACE TRIGGER AT_PUBLISHED_TS_T01
BEFORE INSERT OR UPDATE OF PUBLISHED_ID, TS_CODE ON AT_PUBLISHED_TS
FOR EACH ROW
DECLARE
   l_published_base_param_code NUMBER;
   l_ts_base_param_code        NUMBER;
BEGIN
   SELECT BASE_PARAMETER_CODE
     INTO l_published_base_param_code
     FROM CWMS_PUBLISHED_ID
    WHERE PUBLISHED_ID = :NEW.PUBLISHED_ID;

   SELECT p.BASE_PARAMETER_CODE
     INTO l_ts_base_param_code
     FROM AT_CWMS_TS_SPEC s
     JOIN AT_PARAMETER p ON p.PARAMETER_CODE = s.PARAMETER_CODE
    WHERE s.TS_CODE = :NEW.TS_CODE;

   IF l_published_base_param_code != l_ts_base_param_code THEN
      RAISE_APPLICATION_ERROR(-20001,
         'AT_PUBLISHED_TS: TS_CODE ' || :NEW.TS_CODE ||
         ' base parameter does not match the base parameter of PUBLISHED_ID ' ||
         :NEW.PUBLISHED_ID);
   END IF;
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20002,
         'AT_PUBLISHED_TS: Unable to resolve base parameter for PUBLISHED_ID ' ||
         :NEW.PUBLISHED_ID || ' or TS_CODE ' || :NEW.TS_CODE);
END;
/

CREATE TABLE AT_PUBLISHED_RATING (
    LOCATION_CODE NUMBER(14) NOT NULL,
    PUBLISHED_ID VARCHAR2(24) NOT NULL,
    RATING_SPEC_CODE NUMBER(14) NOT NULL,
    CONSTRAINT AT_PUBLISHED_RATING_PK PRIMARY KEY (LOCATION_CODE, PUBLISHED_ID, RATING_SPEC_CODE) USING INDEX TABLESPACE CWMS_20AT_DATA,
    CONSTRAINT AT_PUBLISHED_RATING_FK_LOC FOREIGN KEY (LOCATION_CODE) REFERENCES AT_PHYSICAL_LOCATION (LOCATION_CODE),
    CONSTRAINT AT_PUBLISHED_RATING_FK_PUB FOREIGN KEY (PUBLISHED_ID) REFERENCES CWMS_PUBLISHED_ID (PUBLISHED_ID),
    CONSTRAINT AT_PUBLISHED_RATING_FK_RATING FOREIGN KEY (RATING_SPEC_CODE) REFERENCES AT_RATING_SPEC (RATING_SPEC_CODE)
) TABLESPACE CWMS_20AT_DATA;

COMMENT ON TABLE AT_PUBLISHED_RATING IS 'Maps locations and published identifiers to their corresponding published ratings';
COMMENT ON COLUMN AT_PUBLISHED_RATING.LOCATION_CODE IS 'Foreign key to AT_PHYSICAL_LOCATION';
COMMENT ON COLUMN AT_PUBLISHED_RATING.PUBLISHED_ID IS 'Foreign key to CWMS_PUBLISHED_ID';
COMMENT ON COLUMN AT_PUBLISHED_RATING.RATING_SPEC_CODE IS 'Foreign key to AT_RATING_SPEC';

-- the base parameter of RATING_SPEC_CODE
-- (via AT_RATING_SPEC -> AT_RATING_TEMPLATE.DEP_PARAMETER_CODE -> AT_PARAMETER)
-- must match the BASE_PARAMETER_CODE of the referenced CWMS_PUBLISHED_ID row.
CREATE OR REPLACE TRIGGER AT_PUBLISHED_RATING_T01
BEFORE INSERT OR UPDATE OF PUBLISHED_ID, RATING_SPEC_CODE ON AT_PUBLISHED_RATING
FOR EACH ROW
DECLARE
   l_published_base_param_code NUMBER;
   l_rating_base_param_code    NUMBER;
BEGIN
   SELECT BASE_PARAMETER_CODE
     INTO l_published_base_param_code
     FROM CWMS_PUBLISHED_ID
    WHERE PUBLISHED_ID = :NEW.PUBLISHED_ID;

   SELECT p.BASE_PARAMETER_CODE
     INTO l_rating_base_param_code
     FROM AT_RATING_SPEC rs
     JOIN AT_RATING_TEMPLATE rt ON rt.TEMPLATE_CODE = rs.TEMPLATE_CODE
     JOIN AT_PARAMETER p ON p.PARAMETER_CODE = rt.DEP_PARAMETER_CODE
    WHERE rs.RATING_SPEC_CODE = :NEW.RATING_SPEC_CODE;

   IF l_published_base_param_code != l_rating_base_param_code THEN
      RAISE_APPLICATION_ERROR(-20003,
         'AT_PUBLISHED_RATING: RATING_SPEC_CODE ' || :NEW.RATING_SPEC_CODE ||
         ' dependent parameter base parameter does not match the base parameter of PUBLISHED_ID ' ||
         :NEW.PUBLISHED_ID);
   END IF;
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20004,
         'AT_PUBLISHED_RATING: Unable to resolve base parameter for PUBLISHED_ID ' ||
         :NEW.PUBLISHED_ID || ' or RATING_SPEC_CODE ' || :NEW.RATING_SPEC_CODE);
END;
/

CREATE TABLE AT_PUBLISHED_LEVEL (
    LOCATION_CODE NUMBER(14) NOT NULL,
    PUBLISHED_ID VARCHAR2(24) NOT NULL,
    LOCATION_LEVEL_CODE NUMBER(14) NOT NULL,
    CONSTRAINT AT_PUBLISHED_LEVEL_PK PRIMARY KEY (LOCATION_CODE, PUBLISHED_ID, LOCATION_LEVEL_CODE) USING INDEX TABLESPACE CWMS_20AT_DATA,
    CONSTRAINT AT_PUBLISHED_LEVEL_FK_LOC FOREIGN KEY (LOCATION_CODE) REFERENCES AT_PHYSICAL_LOCATION (LOCATION_CODE),
    CONSTRAINT AT_PUBLISHED_LEVEL_FK_PUB FOREIGN KEY (PUBLISHED_ID) REFERENCES CWMS_PUBLISHED_ID (PUBLISHED_ID),
    CONSTRAINT AT_PUBLISHED_LEVEL_FK_LEVEL FOREIGN KEY (LOCATION_LEVEL_CODE) REFERENCES AT_LOCATION_LEVEL (LOCATION_LEVEL_CODE)
) TABLESPACE CWMS_20AT_DATA;

COMMENT ON TABLE AT_PUBLISHED_LEVEL IS 'Maps locations and published identifiers to their corresponding published levels';
COMMENT ON COLUMN AT_PUBLISHED_LEVEL.LOCATION_CODE IS 'Foreign key to AT_PHYSICAL_LOCATION';
COMMENT ON COLUMN AT_PUBLISHED_LEVEL.PUBLISHED_ID IS 'Foreign key to CWMS_PUBLISHED_ID';
COMMENT ON COLUMN AT_PUBLISHED_LEVEL.LOCATION_LEVEL_CODE IS 'Foreign key to AT_LOCATION_LEVEL';


-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_ELEV
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_ELEV', 'PUBLISHED', 'Elevation Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Elev';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_PRECIP
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_PRECIP', 'PUBLISHED', 'Precipitation Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Precip';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_STAGE
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_STAGE', 'PUBLISHED', 'Stage Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Stage';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_INFLOW
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_INFLOW', 'PUBLISHED', 'Inflow Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Flow';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_OUTFLOW
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_OUTFLOW', 'PUBLISHED', 'Outflow Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Flow';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_STOR_FLOOD
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_STOR_FLOOD', 'PUBLISHED', 'Flood Storage Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Stor';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_STOR_DROUGHT
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_STOR_DROUGHT', 'PUBLISHED', 'Drought Storage Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Stor';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_SUR_RELEASE
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_SUR_RELEASE', 'PUBLISHED', 'Surcharge Release Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Flow';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_ELEV_TW
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_ELEV_TW', 'PUBLISHED', 'Tailwater Elevation Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Elev';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_STAGE_TW
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_STAGE_TW', 'PUBLISHED', 'Tailwater Stage Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Stage';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_RULE_CURVE_ELEV
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_RULE_CURVE_ELEV', 'PUBLISHED', 'Rule Curve Elevation Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Elev';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_POWER_GEN
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_POWER_GEN', 'PUBLISHED', 'Power Generation Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Power';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_TEMP_AIR
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_TEMP_AIR', 'PUBLISHED', 'Air Temperature Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Temp-Air';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_TEMP_WATER
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_TEMP_WATER', 'PUBLISHED', 'Water Temperature Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Temp-Water';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_DO
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_DO', 'PUBLISHED', 'Dissolved Oxygen Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'DO';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_COND
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_COND', 'PUBLISHED', 'Conductivity Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Cond';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_PH
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_PH', 'PUBLISHED', 'pH Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'pH';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_OPENING
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_OPENING', 'PUBLISHED', 'Opening Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Opening';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_WIND_DIR
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_WIND_DIR', 'PUBLISHED', 'Wind Direction Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Dir';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_WIND_SPEED
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_WIND_SPEED', 'PUBLISHED', 'Wind Speed Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Speed';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_VOLT
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_VOLT', 'PUBLISHED', 'Voltage Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Volt';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_PCT_FLOOD
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_PCT_FLOOD', 'PUBLISHED', 'Flood Percent Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = '%';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_PCT_CON
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_PCT_CON', 'PUBLISHED', 'Conservation Percent Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = '%';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_IRRAD
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_IRRAD', 'PUBLISHED', 'Solar Irradiance Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Irrad';

-- from AT_A2W_TS_CODES_BY_LOC.TS_CODE_EVAP
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'TS_EVAP', 'PUBLISHED', 'Evaporation Time Series', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Evap';

-- from AT_A2W_TS_CODES_BY_LOC.RATING_CODE_ELEV_STOR
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'RATING_ELEV_STOR', 'PUBLISHED', 'Elevation-Storage Rating', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Stor';

-- from AT_A2W_TS_CODES_BY_LOC.RATING_CODE_ELEV_AREA
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'RATING_ELEV_AREA', 'PUBLISHED', 'Elevation-Area Rating', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Area';

-- from AT_A2W_TS_CODES_BY_LOC.RATING_CODE_OUTLET_FLOW
INSERT INTO CWMS_PUBLISHED_ID (PUBLISHED_ID, NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE)
SELECT 'RATING_OUTLET_FLOW', 'PUBLISHED', 'Outlet Flow Rating', BASE_PARAMETER_CODE
FROM CWMS_BASE_PARAMETER WHERE BASE_PARAMETER_ID = 'Flow';

COMMIT;
