/*
 * Copyright (c) 2026
 * United States Army Corps of Engineers - Hydrologic Engineering Center (USACE/HEC)
 * All Rights Reserved.  USACE PROPRIETARY/CONFIDENTIAL.
 * Source may not be released without written approval from HEC
 */

CREATE TABLE CWMS_PUBLISHED_ID (
    PUBLISHED_ID VARCHAR(14) NOT NULL, -- e.g. TS_STOR
    NAMESPACE VARCHAR2(32) NOT NULL, -- e.g. PUBLISHED, REGI, etc.
    PUBLIC_NAME VARCHAR2(128) NOT NULL, -- e.g. Storage Time Series
    BASE_PARAMETER_CODE NUMBER(14) NOT NULL, -- Storage Time Series
    CONSTRAINT CWMS_PUBLISHED_ID_PK PRIMARY KEY (PUBLISHED_ID) USING INDEX TABLESPACE CWMS_20AT_DATA,
    CONSTRAINT CWMS_PUBLISHED_ID_U1 UNIQUE (NAMESPACE, PUBLIC_NAME, BASE_PARAMETER_CODE) USING INDEX TABLESPACE CWMS_20AT_DATA,
    CONSTRAINT CWMS_PUBLISHED_ID_FK1 FOREIGN KEY (BASE_PARAMETER_CODE) REFERENCES AT_PARAMETER (PARAMETER_CODE)
) TABLESPACE CWMS_20AT_DATA;

COMMENT ON TABLE CWMS_PUBLISHED_ID IS 'Reusable published identifier definitions';
COMMENT ON COLUMN CWMS_PUBLISHED_ID.PUBLISHED_ID IS 'Synthetic key for a reusable published identifier';
COMMENT ON COLUMN CWMS_PUBLISHED_ID.NAMESPACE IS 'Namespace that scopes the published identifier';
COMMENT ON COLUMN CWMS_PUBLISHED_ID.PUBLIC_NAME IS 'Public identifier name within the namespace';
COMMENT ON COLUMN CWMS_PUBLISHED_ID.BASE_PARAMETER_CODE IS 'Foreign key to AT_PARAMETER';

CREATE TABLE AT_PUBLISHED_TS (
    LOCATION_CODE NUMBER(14) NOT NULL,
    PUBLISHED_ID VARCHAR(14) NOT NULL,
    TS_CODE NUMBER(14) NOT NULL,
    CONSTRAINT AT_PUBLISHED_TS_PK PRIMARY KEY (LOCATION_CODE, PUBLISHED_ID, TS_CODE) USING INDEX TABLESPACE CWMS_20AT_DATA,
    CONSTRAINT AT_PUBLISHED_TS_FK_LOC FOREIGN KEY (LOCATION_CODE) REFERENCES AT_PHYSICAL_LOCATION (LOCATION_CODE),
    CONSTRAINT AT_PUBLISHED_TS_FK_PUB FOREIGN KEY (PUBLISHED_ID) REFERENCES CWMS_PUBLISHED_ID (PUBLISHED_ID),
    CONSTRAINT AT_PUBLISHED_TS_FK_TS FOREIGN KEY (TS_CODE) REFERENCES AT_CWMS_TS_SPEC (TS_CODE)
) TABLESPACE CWMS_20AT_DATA;

COMMENT ON TABLE AT_PUBLISHED_TS IS 'Maps locations and published identifiers to their corresponding published time series';
COMMENT ON COLUMN AT_PUBLISHED_TS.LOCATION_CODE IS 'Foreign key to AT_PHYSICAL_LOCATION';
COMMENT ON COLUMN AT_PUBLISHED_TS.PUBLISHED_ID IS 'Foreign key to CWMS_PUBLISHED_ID';
COMMENT ON COLUMN AT_PUBLISHED_TS.TS_CODE IS 'Foreign key to AT_CWMS_TS_SPEC';

CREATE TABLE AT_PUBLISHED_RATING (
    LOCATION_CODE NUMBER(14) NOT NULL,
    PUBLISHED_ID VARCHAR(14) NOT NULL,
    RATING_SPEC_CODE NUMBER(14) NOT NULL,
    CONSTRAINT AT_PUBLISHED_RATING_PK PRIMARY KEY (LOCATION_CODE, PUBLISHED_ID, RATING_SPEC_CODE) USING INDEX TABLESPACE CWMS_20AT_DATA,
    CONSTRAINT AT_PUBLISHED_RATING_FK_LOC FOREIGN KEY (LOCATION_CODE) REFERENCES AT_PHYSICAL_LOCATION (LOCATION_CODE),
    CONSTRAINT AT_PUBLISHED_RATING_FK_PUB FOREIGN KEY (PUBLISHED_ID) REFERENCES CWMS_PUBLISHED_ID (PUBLISHED_ID),
    CONSTRAINT AT_PUBLISHED_RATING_FK_RATING FOREIGN KEY (RATING_SPEC_CODE) REFERENCES AT_RATING_SPEC (RATING_SPEC_CODE)
) TABLESPACE CWMS_20AT_DATA;

COMMENT ON TABLE AT_PUBLISHED_RATING IS 'Maps locations and published identifiers to their corresponding published ratings';
COMMENT ON COLUMN AT_PUBLISHED_RATING.LOCATION_CODE IS 'Foreign key to AT_PHYSICAL_LOCATION';
COMMENT ON COLUMN AT_PUBLISHED_RATING.PUBLISHED_ID IS 'Foreign key to CWMS_PUBLISHED_ID';
COMMENT ON COLUMN AT_PUBLISHED_RATING.RATING_SPEC_CODE IS 'Foreign key to AT_RATING_SPEC';

CREATE TABLE AT_PUBLISHED_LEVEL (
    LOCATION_CODE NUMBER(14) NOT NULL,
    PUBLISHED_ID VARCHAR(14) NOT NULL,
    LOCATION_LEVEL_CODE NUMBER(14) NOT NULL,
    CONSTRAINT AT_PUBLISHED_LEVEL_PK PRIMARY KEY (LOCATION_CODE, PUBLISHED_ID, LOCATION_LEVEL_CODE) USING INDEX TABLESPACE CWMS_20AT_DATA,
    CONSTRAINT AT_PUBLISHED_LEVEL_FK_LOC FOREIGN KEY (LOCATION_CODE) REFERENCES AT_PHYSICAL_LOCATION (LOCATION_CODE),
    CONSTRAINT AT_PUBLISHED_LEVEL_FK_PUB FOREIGN KEY (PUBLISHED_ID) REFERENCES CWMS_PUBLISHED_ID (PUBLISHED_ID),
    CONSTRAINT AT_PUBLISHED_LEVEL_FK_LEVEL FOREIGN KEY (LOCATION_LEVEL_CODE) REFERENCES AT_LOCATION_LEVEL (LOCATION_LEVEL_CODE)
) TABLESPACE CWMS_20AT_DATA;

COMMENT ON TABLE AT_PUBLISHED_LEVEL IS 'Maps locations and published identifiers to their corresponding published levels';
COMMENT ON COLUMN AT_PUBLISHED_LEVEL.LOCATION_CODE IS 'Foreign key to AT_PHYSICAL_LOCATION';
COMMENT ON COLUMN AT_PUBLISHED_LEVEL.PUBLISHED_ID IS 'Foreign key to CWMS_PUBLISHED_ID';
COMMENT ON COLUMN AT_PUBLISHED_LEVEL.LOCATION_LEVEL_CODE IS 'Foreign key to AT_LOCATION_LEVEL';
