/*
 * Copyright (c) 2026
 * United States Army Corps of Engineers - Hydrologic Engineering Center (USACE/HEC)
 * All Rights Reserved.  USACE PROPRIETARY/CONFIDENTIAL.
 * Source may not be released without written approval from HEC
 */

CREATE TABLE AT_PUBLISHED_TS (
    LOCATION_CODE NUMBER(14) NOT NULL,
    PARAMETER_CODE NUMBER(14) NOT NULL,
    TS_CODE NUMBER(14) NOT NULL,
    CONSTRAINT AT_PUBLISHED_TS_PK PRIMARY KEY (LOCATION_CODE, PARAMETER_CODE),
    CONSTRAINT AT_PUBLISHED_TS_FK_LOC FOREIGN KEY (LOCATION_CODE) REFERENCES AT_PHYSICAL_LOCATION (LOCATION_CODE),
    CONSTRAINT AT_PUBLISHED_TS_FK_PARAM FOREIGN KEY (PARAMETER_CODE) REFERENCES AT_PARAMETER (PARAMETER_CODE),
    CONSTRAINT AT_PUBLISHED_TS_FK_TS FOREIGN KEY (TS_CODE) REFERENCES AT_CWMS_TS_SPEC (TS_CODE)
) TABLESPACE CWMS_20DATA;

COMMENT ON TABLE AT_PUBLISHED_TS IS 'Maps locations and parameters to their corresponding published time series';
COMMENT ON COLUMN AT_PUBLISHED_TS.LOCATION_CODE IS 'Foreign key to AT_PHYSICAL_LOCATION';
COMMENT ON COLUMN AT_PUBLISHED_TS.PARAMETER_CODE IS 'Foreign key to AT_PARAMETER';
COMMENT ON COLUMN AT_PUBLISHED_TS.TS_CODE IS 'Foreign key to AT_CWMS_TS_SPEC';
